name: CI Test Workflow

on:
  pull_request

env:
  GITHUB_ACTIONS: true

jobs:
  github-task-job:
    runs-on: ubuntu-latest
    steps:
      - name: Author name
        run: |
          echo "Author name: ${{ github.actor }}"

      - name: Show GITHUB_ACTIONS environment variable
        run: echo "GITHUB_ACTIONS=$GITHUB_ACTIONS"

      - name: Show branch name and repository
        run: |
          echo "Branch name: ${{ github.head_ref }}"
          echo "Repository: ${{ github.repository }}"

      - name: Show triggering event
        run: |
          echo "Event name: ${{ github.event_name }}"